project_id = "yhwrcbiemftwbklgvfzi"

[functions.setup-admin]
verify_jwt = false

[functions.validate-order]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.guest-order-lookup]
verify_jwt = false

[functions.ai-chat-reply]
verify_jwt = true

[functions.customer-chat-reply]
verify_jwt = false

[functions.require-admin]
verify_jwt = false